- requirements/local.txt
Accidentally merged a PR that broke CI, since we're running python 3.8.
> Use a sphinx version that supports Python 3.8

- requirements/requirements.in
Hopefully this will allow pip-compile/dependabot to include the ACM requirements as well. We are security alerts that dependabot can't install, I think because it thinks the django-anvil-consortium-manager repo is private?
> Fix specification of ACM in requirements.in file

- requirements/dev-requirements.txt
- requirements/requirements.in
- requirements/requirements.txt
- requirements/test-requirements.txt
The automatic security update failed because dependabot couldn't update dependencies that are only dependencies of ACM. Not entirely sure why, so fixing manually for now.
> Update certifi version to 2023.7.22

- .github/dependabot.yml
By default all dependencies that are explicitly defined in a manifest are kept up to date by Dependabot version updates. We got a security update that reported:
"This is an indirect dependency not explicitly present in any manifest file, so Dependabot cannot update it."
so try adding dependency-type to the dependabot config.
> Allow both direct and indirect dependabot updates

- requirements/requirements.in
- requirements/requirements.txt
The security alert couldn't automatically resolve this for the following reason:
> Dependabot can't find the vulnerable dependency in the repository.
> This is an indirect dependency not explicitly present in any manifest file, so Dependabot cannot update it.
> Pin minimum version of pyjwt to fix security alert

- requirements/requirements.in
- requirements/requirements.txt
django-environ>=0.11 introduces a bug where secret keys in a file that have a hash character in them are truncated. Downgrade to django-environ 0.10.0 to fix this for now.
See https://github.com/joke2k/django-environ/issues/497
> Pin django-environ to working version

- .github/workflows/ci.yml
Since we're not running MariaDB 10.3 anymore, we don't need to test agianst it.
> Remove MariaDB 10.3 from CI

- gregor_django/users/tests/factories.py
factoryboy is deprecating save after post-generation in v3.3.0. Handle the new warnings following their advice:
https://factoryboy.readthedocs.io/en/stable/changelog.html#id1
> Handle factoryboy postgeneration updates

- requirements/dev-requirements.txt
- requirements/requirements.in
- requirements/requirements.txt
Update requirements.in to pin to any version of 4.2, and then recompile all the requriements files.
> Django 4.2

- .github/workflows/gitleaks.yml
- .pre-commit-config.yaml
Because these repositories are in the UW-GAC organization, I also needed to obtain for a gitleaks license and add it as a secret in the UW-GAC organization.
Closes #339
> Add a gitleaks actions

- requirements/requirements.in
- requirements/requirements.txt
Removing it broke logins to the admin interface.
> Add argon2-cffi back to requirements

- requirements/requirements.in
- requirements/requirements.txt
This update fixes a bug where the permissions of the maintenance mode state file are not properly maintained (due to the implementation in python-fsutil). v0.21.1 of django maintenance mode requires the version of python-fsutil where this bug is fixed. See fabiocaccamo/django-maintenance-mode#172 for info.
> Update to latest version of django-maintenance-mode

- config/settings/base.py
- gregor_django/gregor_anvil/tests/test_views.py
- gregor_django/templates/base.html
- requirements/requirements.in
- requirements/requirements.txt
- Use the django-constance app to add settings that can be edited in the admin
- Add a SITE_ANNOUNCEMENT setting
- If SITE_ANNOUNCEMENT is non-blank, show an alert with the text of the site announcement
> Add ability to show site-wide banner announcements

- requirements/dev-requirements.in
- requirements/dev-requirements.txt
Should have been part of the ruff branch, so just cleaning up packages.
Note: I had to do this manually, since I currently can't run pip-compile locally.
> Remove black and flake8 from requirements

- requirements/dev-requirements.in
dependabot tried to update this to v5.0 but we are using Django 4.2.
> Pin django stubs to a version matching django 4.2

- .github/workflows/ci.yml
- config/settings/base.py
- config/settings/local.py
- config/settings/production.py
This way we only have to modify one CI job if we want to change something, add a new strategy, etc.
> Combine mysql and sqlite tests into a single job

- .github/workflows/ci.yml
- Add a step to the CI that (optionally) reruns pip-compile on the requirements.in files
- Add a `pip-recompile` setting to the matrix definitions that can be used to toggle whether this step should run.
The pip-recompile setting can be set to true when we want to test future versions of python compared to what is running on the live servers.
> Add optional step to recompile pip tools in CI

- .github/workflows/ci.yml
- gregor_django/drupal_oauth_provider/tests.py
- pytest.ini
- requirements/requirements.in
- requirements/requirements.txt
- Run python3.12 in additional CI strategies
- Upgrade to ACM v0.22.1, which fixes an issue with numpy/setuptools in python3.12
- Fix various DeprecationWarnings from third party packages
> Run python3.12 in additional CI strategies

- .github/workflows/pip-compile.yml
Add a new workflow for pull requests into main that:
* compiles the requirements files
* opens a pull request if changes are detected
* exits successfully (if no changes are detected) or unsuccessfully (if changes are detected)
> Set up CI to run pip-compile, check for changes, and open a pull request

- gregor_django/templates/users/user_detail.html
The page should have been using the context user_email_entries object instead of accessing it from the user, because the context object filters out verified emails that are no longer linked. This caused the warning about no linked account to be hidden.
> Fix issue with account link on profile page

- gregor_django/gregor_anvil/tests/test_views.py
- gregor_django/gregor_anvil/views.py
The tables of members with data access and uploaders were incorrect when the groups were not set - instead, it showed all accounts. Fix this in the view and add tests to catch this case.
> Fix member and upload tables when groups are not set

- gregor_django/gregor_anvil/tests/test_views.py
- gregor_django/gregor_anvil/views.py
The site user table showed inactive users associated with the ResearchCenter or PartnerGroup. Filter them out in the table queryset so the table only shows active users.
> Hide inactive users in ResearchCenter and PartnerGroup detail views

- gregor-apps-activate.sh
- gregor-apps-dev-activate.sh
That we can we can reference it with an environment variable when deploying.
> Add the crontab file to the activate script

- .github/dependabot.yml
Since we're now using the action to combine dependabot PRs into a single PR, it's ok if dependabot runs more frequently.
> Run dependabot nightly

- .github/workflows/pip-compile.yml
This should(?) allow the create-pull-request action to run and create a PR on dependabot updates. (This mostly affects security updates?)
> Add permissions for pip-compile workflow

- config/settings/base.py
- config/settings/local.py
- config/settings/production.py
- config/settings/test.py
- gregor_django/gregor_anvil/adapters.py
- gregor_django/gregor_anvil/tests/test_adapters.py
- gregor_django/gregor_anvil/tests/test_views.py
- Add Workspace adapter methods to automatically share any workspaces that was created or imported with the DCC admins group
- Add ManagedGroup adapter methods to automatically add the DCC admins group to any managed group created via the ManagedGroupCreate view
> Automate adding DCC admins group to workspaces and managed groups

- gregor_apps.cron
- Send errors by email instead of redirecting to stdout
- Change the time that the audits run at
> Cron updates

- .github/workflows/combine-prs.yml
It is better to review the dependabot PRs, close any that we do not want included in the combined update, and then run the combine-prs workflow manually (via workflow dispatch). This way we won't inadvertently get updates that we don't want (e.g., a passing PR that updates to django-5.0).
> Do not schedule combine-prs workflow

- gregor_django/gregor_anvil/views.py
This view was using the template for the upload workspace sharing audit instead of the auth domain audit. The behavior of the view is fine since the templates are very similar; it's just that the explanation and title are incorrect.
> Fix template for UploadWorkspaceAuthDomainAudit view

- .github/workflows/ci.yml
- gregor_django/gregor_anvil/audit/upload_workspace_sharing_audit.py
- gregor_django/gregor_anvil/tests/test_audit.py
- gregor_django/gregor_anvil/tests/test_views.py
- gregor_django/templates/gregor_anvil/snippets/upload_workspace_auth_domain_audit_explanation.html
- gregor_django/templates/gregor_anvil/snippets/upload_workspace_sharing_audit_explanation.html
- gregor_django/templates/gregor_anvil/upload_workspace_auth_domain_audit.html
- gregor_django/templates/gregor_anvil/upload_workspace_sharing_audit.html
- Only show the can_compute icon for WRITER and OWNER levels
- Color the false icons black instead of red, since they don't indicate errors
- Clean up audit explanations
- Clean up unused code
- Add tests for audit result dataclasses
> Upload workspace audit - user feedback

- .github/workflows/ci.yml
- .github/workflows/gitleaks.yml
- .github/workflows/pip-compile.yml
This way, they should get updated via dependabot and then we can fix any issues with new versions in the dependabot branch, instead of in a random branch after something changes.
> Pin github actions to full versions in workflows

- gregor_django/templates/socialaccount/authentication_error.html
- gregor_django/users/adapters.py
Add logging to our social account adapter so we can capture when there are cert or other login cycle issues.
Update auth error template to display more information about the login error.
> Add auth cycle error logging 

- config/settings/base.py
- gregor_django/drupal_oauth_provider/provider.py
- gregor_django/drupal_oauth_provider/tests.py
- gregor_django/drupal_oauth_provider/views.py
- gregor_django/templates/socialaccount/authentication_error.html
- gregor_django/users/adapters.py
- gregor_django/users/tests/test_adapters.py
- gregor_django/users/tests/test_views.py
- gregor_django/users/views.py
- requirements/requirements.in
- requirements/requirements.txt
Upgrades to our drupal oauth allauth provider and adapters to work with the upgraded version of allauth
> django-allauth upgrade integration fixes

- .github/workflows/pip-compile.yml
This fixes an issue with pip-tools and pip versions, where pip-copmile was adding absolute paths when run with a pip version of >=24.3.
> Use new version of update-requirements-files action

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
- Add the release-drafter action to draft release notes on a commit/merge to deploy/prod
- Name the draft release and tag with the current date (e.g., 2024-12-05) or current with an integer appended (e.g., 2024-12-05-1, 2024-12-05-2, etc) if a release with the date already exists
- Set up config to separate dependency PRs in their own section in the release notes
> Use release-drafter action to draft releases and notes

- config/settings/base.py
- requirements/requirements.in
- requirements/requirements.txt
This adds the ability to ignore AnVIL audit "not in app" results.
> Update to ACM v0.28

- .github/workflows/ci.yml
- config/settings/base.py
- config/settings/production.py
Fail on warnings. Ignore current warnings that we are aware of. Optimally we could ignore the specific issue and not a class of warnings but django does not currently support that.
> Add django db check to ci

- gregor_django/gregor_anvil/adapters.py
- gregor_django/gregor_anvil/tests/test_adapters.py
- gregor_django/templates/gregor_anvil/account_notification_email.html
- Use the new AccountAdapter functionality to automatically add a user to their RC or partner group  group(s) fo rmembers after they link their account.
- Show the list of groups that an Account belongs to in the account verification notification email to the DCC
> Automatically add accounts to members groups
